backend:
  name: git-gateway
  branch: main
  repo: smpkartikaxiv1-cloud/bandaaceh

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "page"
    label: "Halaman"
    files:
            - file: "index.html"
        label: "Beranda"
        name: "beranda"
        fields:
                    - {label: "Judul", name: "title", widget: "string"}
                    - {label: "Konten", name: "body", widget: "markdown"}